"""Changed channel in messages to channel id to avoid clashing with the channel in backref channel class

Revision ID: ecd80383e932
Revises: 
Create Date: 2020-05-08 13:07:43.915852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd80383e932'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('channel_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_channel_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'channels', ['channel_id'], ['id'])
    op.drop_column('messages', 'channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('channel', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_channel_fkey', 'messages', 'channels', ['channel'], ['id'])
    op.drop_column('messages', 'channel_id')
    # ### end Alembic commands ###
